### ISSUE TITLE
Le manuel est obsolète

### ISSUE THREAD

**Issue by Evpok** [YoannDupont/SEM#1]
Le manuel actuel ne prend pas en compte les changements effectués pour la version 2.4. Et comme la source n'est pas dispo… 😁

**Comment by auroredea** [comment]
See https://github.com/YoannDupont/SEM/commit/39c166f4d85e68b6380ccbf9d9221a7acb1dbbf4

**Comment by YoannDupont** [comment]
See commit fec176c31fb09a19d86ba339d3d915884775bda4
