### ISSUE TITLE
Coding style improvement

### ISSUE THREAD

**Issue by YoannDupont** [YoannDupont/SEM#12]
More time being spent reading code than writing it, coding style should follow more closely PEP8 recommendations.

**Comment by Evpok** [comment]
Time to paint it black, Dupont.

**Comment by YoannDupont** [comment]
That's the plan. Too bad SEM is not a rolling release. I guess it will more be SEM v4: blackened.

**Comment by YoannDupont** [comment]
Done in commit [d09e536](https://github.com/YoannDupont/SEM/commit/d09e53615ff7eaf0114b563536ffa36538c7afbf).
